spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor # sochopp
    username: root
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
